/*
 * generated by Xtext 2.33.0
 */
/*
 * Copyright (c) 2022 - 2024 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

import com.epistimis.uddl.uddl.LogicalEnumerationLabel;

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
public class UddlOutlineTreeProvider extends DefaultOutlineTreeProvider {

	protected boolean _isLeaf(LogicalEnumerationLabel lbl) {
		return true;
	}
	
}
