/*
 * generated by Xtext 2.33.0
 */
/*
 * Copyright (c) 2022 - 2024 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.web;

import com.epistimis.uddl.UddlRuntimeModule;
import com.epistimis.uddl.UddlStandaloneSetup;
import com.epistimis.uddl.ide.UddlIdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class UddlWebSetup extends UddlStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new UddlRuntimeModule(), new UddlIdeModule(), new UddlWebModule()));
	}
	
}
