/*
 * generated by Xtext 2.33.0
 */
/*
 * Copyright (c) 2022 - 2024 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class UddlWebModule extends AbstractUddlWebModule {
}
