/*
 * generated by Xtext 2.33.0
 */
/*
 * Copyright (c) 2022 - 2024 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.documentation.IEObjectDocumentationProvider;
import org.eclipse.xtext.ui.editor.hover.IEObjectHover;
import org.eclipse.xtext.ui.editor.hover.IEObjectHoverProvider;

import com.epistimis.uddl.ui.contentassist.CLRealizationProposalProcessor;
import com.epistimis.uddl.ui.contentassist.LPRealizationProposalProcessor;
import com.epistimis.uddl.ui.contentassist.PropUtils;
import com.epistimis.uddl.ui.hover.UddlDispatchingEObjectTextHover;
import com.epistimis.uddl.ui.hover.UddlEObjectDocumentationProvider;
import com.epistimis.uddl.ui.hover.UddlEObjectHoverProvider;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class UddlUiModule extends AbstractUddlUiModule {

	public UddlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	public Class<? extends IEObjectHover> bindIEObjectHover() {
		return UddlDispatchingEObjectTextHover.class;
	}

	public Class<? extends IEObjectHoverProvider> bindIEObjectHoverProvider() {
		return UddlEObjectHoverProvider.class;
	}

	public Class<? extends IEObjectDocumentationProvider> bindIEObjectDocumentationProvider() {
		return UddlEObjectDocumentationProvider.class;
	}
	
	public Class<? extends CLRealizationProposalProcessor> bindCLRealizationProposalProcessor() {
		return CLRealizationProposalProcessor.class;
	}

	public Class<? extends LPRealizationProposalProcessor> bindLPRealizationProposalProcessor() {
		return LPRealizationProposalProcessor.class;
	}

	public Class<? extends PropUtils> bindPropUtils() {
		return PropUtils.class;
	}

}
